name: Push directory to another repository
description: >-
  Useful to push files to another repository to be used, for example, via github
  pages
inputs:
  repository-uri:
    required: true
    description: Target repository URI
  username:
    required: true
    description: Target repository username
  token:
    required: true
    description: Target repository token or password
  branch:
    required: true
    description: Target repository branch
runs:
  using: docker
  image: Dockerfile
  args:
    - '${{ inputs.repository-uri }}'
    - '${{ inputs.username }}'
    - '${{ inputs.token }}'
    - '${{ inputs.branch }}'
branding:
  icon: git-commit
  color: green
